// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound backend service. All exported methods are callable
 * from the frontend via generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelTransfer(): $CancellablePromise<void> {
    return $Call.ByID(959861416);
}

/**
 * ClearHistory removes all recorded history entries.
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(3429172794);
}

/**
 * ClearLogs empties the log buffer.
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1566804265);
}

/**
 * DecodeCodeFromBase64 decodes a base64-encoded image (e.g. a pasted
 * clipboard screenshot) and returns the text of the QR code in it.
 */
export function DecodeCodeFromBase64(b64: string): $CancellablePromise<string> {
    return $Call.ByID(335550797, b64);
}

/**
 * DecodeCodeFromFile reads an image file and returns the text of the QR code
 * in it (typically the croc code phrase). The image is never shown to the
 * user — it is only used to extract the code.
 */
export function DecodeCodeFromFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1891733924, path);
}

export function GetDefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(658010303);
}

/**
 * GetFileDataURL reads a local file and returns it as a data: URL so the
 * frontend can preview received media without a local file server.
 */
export function GetFileDataURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(519099618, path);
}

/**
 * GetHistory returns the recorded transfer history, newest first.
 */
export function GetHistory(): $CancellablePromise<$models.historyItem[]> {
    return $Call.ByID(210907985).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogs returns the buffered log entries, oldest first.
 */
export function GetLogs(): $CancellablePromise<$models.logEntry[]> {
    return $Call.ByID(1743981476).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetQrPng returns a base64-encoded PNG QR code for the given text.
 */
export function GetQrPng(text: string): $CancellablePromise<string> {
    return $Call.ByID(490057439, text);
}

export function GetRelayState(): $CancellablePromise<$models.relayState> {
    return $Call.ByID(1631671617).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * IsTransferRunning reports whether a transfer is in progress; used by the
 * E2E harness to wait for the backend to settle between tests.
 */
export function IsTransferRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2772654525);
}

/**
 * NormalizeCode exposes normalizeCodeInput to the frontend so pasted receive
 * instructions "just work".
 */
export function NormalizeCode(input: string): $CancellablePromise<string> {
    return $Call.ByID(3243208913, input);
}

/**
 * PathsIsDir reports which of the given paths are directories, so the UI can
 * show folder icons for them.
 */
export function PathsIsDir(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2780421882, paths).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1347829059);
}

export function PickFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(4162647679).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PickImage opens a native file dialog filtered to image files.
 */
export function PickImage(): $CancellablePromise<string> {
    return $Call.ByID(929721757);
}

export function RespondAccept(accept: boolean): $CancellablePromise<void> {
    return $Call.ByID(3466043470, accept);
}

export function RespondOverwrite(overwrite: boolean): $CancellablePromise<void> {
    return $Call.ByID(291544723, overwrite);
}

export function SaveSettings(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, s);
}

/**
 * StartReceive connects with the given code phrase and receives into outDir.
 * Progress and prompts arrive as events.
 */
export function StartReceive(code: string, outDir: string): $CancellablePromise<void> {
    return $Call.ByID(3272686060, code, outDir);
}

export function StartRelay(ports: string[], password: string): $CancellablePromise<void> {
    return $Call.ByID(2201975092, ports, password);
}

/**
 * StartSend begins sending the given files/folders and returns the code
 * phrase the recipient should enter.
 */
export function StartSend(paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(1052991585, paths);
}

/**
 * StartSendText sends a text snippet; it is wrapped in a temp file, matching
 * the CLI's --text behavior.
 */
export function StartSendText(text: string): $CancellablePromise<string> {
    return $Call.ByID(3419514034, text);
}

export function StopRelay(): $CancellablePromise<void> {
    return $Call.ByID(2771655530);
}

// Private type creation functions
const $$createType0 = $models.historyItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.logEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.relayState.createFrom;
const $$createType5 = $models.Settings.createFrom;
const $$createType6 = $Create.Array($Create.Any);
