// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo is shown on the Settings page (version + engine + defaults).
 */
export class AppInfo {
    "version": string;
    "crocVersion": string;
    "defaultRelay": string;
    "defaultRelay6": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("crocVersion" in $$source)) {
            this["crocVersion"] = "";
        }
        if (!("defaultRelay" in $$source)) {
            this["defaultRelay"] = "";
        }
        if (!("defaultRelay6" in $$source)) {
            this["defaultRelay6"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * SavedCode is a remembered receive code (favorite), managed from the
 * Receive view.
 */
export class SavedCode {
    "name": string;
    "code": string;

    /** Creates a new SavedCode instance. */
    constructor($$source: Partial<SavedCode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedCode instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedCode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedCode($$parsedSource as Partial<SavedCode>);
    }
}

/**
 * Settings holds the user-configurable options shown in the Settings view.
 * It maps onto croc.Options; see buildCrocOptions.
 */
export class Settings {
    "relayAddress": string;
    "relayAddress6": string;
    "relayPassword": string;
    "curve": string;
    "hashAlgorithm": string;
    "onlyLocal": boolean;
    "disableLocal": boolean;
    "noCompress": boolean;
    "overwrite": boolean;
    "downloadDir": string;
    "socks5": string;
    "httpProxy": string;
    "zipFolder": boolean;
    "exclude": string;
    "throttleUpload": string;
    "ip": string;

    /**
     * system | light | dark
     */
    "theme": string;

    /**
     * system | <locale>, e.g. en, zh-CN
     */
    "language": string;
    "savedCodes"?: SavedCode[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("relayAddress" in $$source)) {
            this["relayAddress"] = "";
        }
        if (!("relayAddress6" in $$source)) {
            this["relayAddress6"] = "";
        }
        if (!("relayPassword" in $$source)) {
            this["relayPassword"] = "";
        }
        if (!("curve" in $$source)) {
            this["curve"] = "";
        }
        if (!("hashAlgorithm" in $$source)) {
            this["hashAlgorithm"] = "";
        }
        if (!("onlyLocal" in $$source)) {
            this["onlyLocal"] = false;
        }
        if (!("disableLocal" in $$source)) {
            this["disableLocal"] = false;
        }
        if (!("noCompress" in $$source)) {
            this["noCompress"] = false;
        }
        if (!("overwrite" in $$source)) {
            this["overwrite"] = false;
        }
        if (!("downloadDir" in $$source)) {
            this["downloadDir"] = "";
        }
        if (!("socks5" in $$source)) {
            this["socks5"] = "";
        }
        if (!("httpProxy" in $$source)) {
            this["httpProxy"] = "";
        }
        if (!("zipFolder" in $$source)) {
            this["zipFolder"] = false;
        }
        if (!("exclude" in $$source)) {
            this["exclude"] = "";
        }
        if (!("throttleUpload" in $$source)) {
            this["throttleUpload"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField18_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("savedCodes" in $$parsedSource) {
            $$parsedSource["savedCodes"] = $$createField18_0($$parsedSource["savedCodes"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class historyFile {
    "name": string;

    /**
     * absolute, for previews
     */
    "path"?: string;
    "size": number;

    /** Creates a new historyFile instance. */
    constructor($$source: Partial<historyFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new historyFile instance from a string or object.
     */
    static createFrom($$source: any = {}): historyFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new historyFile($$parsedSource as Partial<historyFile>);
    }
}

export class historyItem {
    "id": string;
    "time": Date;

    /**
     * send | receive
     */
    "direction": string;

    /**
     * completed | cancelled | error
     */
    "status": string;
    "error"?: string;
    "isText"?: boolean;
    "text"?: string;
    "files"?: historyFile[];
    "totalFiles"?: number;
    "totalSize"?: number;

    /**
     * receive destination
     */
    "dir"?: string;

    /** Creates a new historyItem instance. */
    constructor($$source: Partial<historyItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new historyItem instance from a string or object.
     */
    static createFrom($$source: any = {}): historyItem {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("time" in $$parsedSource) {
            $$parsedSource["time"] = $$createField1_0($$parsedSource["time"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField7_0($$parsedSource["files"]);
        }
        return new historyItem($$parsedSource as Partial<historyItem>);
    }
}

export class logEntry {
    "id": string;
    "time": Date;

    /**
     * debug | info | warn | error
     */
    "level": string;
    "source": string;
    "message": string;

    /** Creates a new logEntry instance. */
    constructor($$source: Partial<logEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new logEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): logEntry {
        const $$createField1_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("time" in $$parsedSource) {
            $$parsedSource["time"] = $$createField1_0($$parsedSource["time"]);
        }
        return new logEntry($$parsedSource as Partial<logEntry>);
    }
}

export class relayState {
    "running": boolean;
    "ports"?: string[];
    "error"?: string;

    /** Creates a new relayState instance. */
    constructor($$source: Partial<relayState> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new relayState instance from a string or object.
     */
    static createFrom($$source: any = {}): relayState {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField1_0($$parsedSource["ports"]);
        }
        return new relayState($$parsedSource as Partial<relayState>);
    }
}

// Private type creation functions
const $$createType0 = SavedCode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = historyFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
